Default: &defaults
  database: almoco-tecnico.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: almoco-tecnico_test.sqlite3
  <<: *defaults

Staging:
  database: almoco-tecnico_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: almoco-tecnico_production.sqlite3
  poolsize: 100
  <<: *defaults
